export const API_URL = 'http://localhost:3001';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDERS_SUCCESS = 'CREATE_ORDERS_SUCCESS';
export const CREATE_ORDERS_FAILURE = 'CREATE_ORDERS_FAILURE';

export const FETCH_FORM_DATA_REQUEST = 'FETCH_FORM_DATA_REQUEST';
export const FETCH_FORM_DATA_SUCCESS = 'FETCH_FORM_DATA_SUCCESS';
export const FETCH_FORM_DATA_FAILURE = 'FETCH_FORM_DATA_FAILURE';

export const CHANGE_CREATE_ORDER_STATUS = 'CHANGE_CREATE_ORDER_STATUS';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDERS_SUCCESS = 'UPDATE_ORDERS_SUCCESS';
export const UPDATE_ORDERS_FAILURE = 'UPDATE_ORDERS_FAILURE';

export const CLEAR_ORDER_LIST = 'CLEAR_ORDER_LIST';

