export const API_URL = 'http://localhost:3001';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDERS_SUCCESS = 'CREATE_ORDERS_SUCCESS';
export const CREATE_ORDERS_FAILURE = 'CREATE_ORDERS_FAILURE';

export const FETCH_FORM_DATA_REQUEST = 'FETCH_FORM_DATA_REQUEST';
export const FETCH_FORM_DATA_SUCCESS = 'FETCH_FORM_DATA_SUCCESS';
export const FETCH_FORM_DATA_FAILURE = 'FETCH_FORM_DATA_FAILURE';

export const CHANGE_CREATE_ORDER_STATUS = 'CHANGE_CREATE_ORDER_STATUS';

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST';
export const UPDATE_ORDERS_SUCCESS = 'UPDATE_ORDERS_SUCCESS';
export const UPDATE_ORDERS_FAILURE = 'UPDATE_ORDERS_FAILURE';

export const CLEAR_ORDER_LIST = 'CLEAR_ORDER_LIST';

